// <auto-generated />
using System;
using ChargingStation.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChargingStation.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChargingStation.API.Domain.Entities.ChargingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectorType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LocationAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LocationLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChargingStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectorType = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://placehold.co/400x200?text=Station+1",
                            LocationAddress = "MG Road, Pune",
                            LocationLink = "https://maps.google.com/?q=MG+Road+Pune",
                            Name = "Pune Central Hub",
                            PinCode = "411001",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            ConnectorType = 1,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://placehold.co/400x200?text=Station+2",
                            LocationAddress = "Baner Road, Pune",
                            LocationLink = "https://maps.google.com/?q=Baner+Road+Pune",
                            Name = "Baner EV Point",
                            PinCode = "411045",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            ConnectorType = 2,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://placehold.co/400x200?text=Station+3",
                            LocationAddress = "Hinjewadi Phase 1, Pune",
                            LocationLink = "https://maps.google.com/?q=Hinjewadi+Pune",
                            Name = "Hinjewadi Tech Park",
                            PinCode = "411057",
                            Status = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
